### PR TITLE
Add cmake install

### PR DESCRIPTION
**Pull request by miyanyan**
* add the cmake install code
* I got an error when run cmake_build.py, so I changed `include_directories(${CMAKE_CURRENT_LIST_DIR}/../pocketpy/include)`in 3rd/cjson/CMakeLists.txt, and tested it on linux and window

also add to vcpkg https://github.com/microsoft/vcpkg/pull/36829

### CODE REVIEW

**Comment by blueloveTH** [comment]
CI seems failed.

**Comment by miyanyan** [comment]
hi, I run the action but ci passed, i'm a little confused...
https://github.com/miyanyan/pocketpy/actions/runs/7949484566
https://github.com/miyanyan/pocketpy/actions/runs/7949451037

**Comment by blueloveTH** [comment]
Thanks for your work. I approve this pr.

**Comment by miyanyan** [comment]
There's some python issues on windows when I add to vcpkg, maybe caused by vcpkg's python port strategy.
And I see this commit [remove python3 deps](https://github.com/pocketpy/pocketpy/commit/92705058b21efccdd645aeefc550d71d00c228f5), this commit may helps so I can wait for the new release~

**Pull request merged**
