### PR TITLE
fix bugs

### PR DESCRIPTION
**Pull request by AstroAir**
-- fix some compile bugs
-- modified README_zh.md

### CODE REVIEW

**Comment by blueloveTH** [comment]
Hello @AstroAir .

You have changed a lot of files and this could break our code. This pr won't be accepted until discussion / detailed description.

**Comment by AstroAir** [comment]
I'm sorry I didn't provide a detailed explanation. All modifications were made by adding [maybe_unused] and converting size_t to int when comparing it to int (using static_cast). After modification, all unit tests passed.

**Comment by AstroAir** [comment]
I'm sorry I didn't provide a detailed explanation. All modifications were made by adding [maybe_unused] and converting size_t to int when comparing it to int (using static_cast). After modification, all unit tests passed.

**Comment by AstroAir** [comment]
Overall, no modifications were made to the logic or implementation of the running code. If it is not possible to merge, can I update the document first and then discuss the issue of compilation warnings?

**Pull request closed without merging**
