### PR TITLE
Perform boundary checks before searching to prevent security vulnerabilities

### PR DESCRIPTION
**Pull request by albertexye**
The current str.find doesn't perform boundary checks, which can lead to a crash or even security issues. 
A simple way to reproduce this bug: "hello".find('lo', -100000)
Instead, -1 should be returned in this case.

### CODE REVIEW

**Comment by blueloveTH** [comment]
Does cpython return -1 for this case?

**Comment by albertexye** [comment]
Oh it doesn't. But CPython doesn't actually try to access that memory.

**Comment by blueloveTH** [comment]
Not correct. cpython treat start and end as slice arguments. So `-1` means the last char not `0`.

However, we don't want to make this complicated. The optimal fix is to raise a `ValueError`.

**Comment by albertexye** [comment]
Yeah you are right.

**Comment by blueloveTH** [comment]
Thank you for your work `:)`

**Pull request merged**
